---
- hosts: all
  name: Set Internal Repo
  vars:
    repository_name: "cpanel-plugins"
    repo_url_rhel: "https://[REDACTED]/home:/bamboo:/cpanel-plugins:/{{ plugin_branch }}/CentOS_$cp_centos_major_version"
    repo_url_ubuntu: "https://[REDACTED]/home:/bamboo:/cpanel-plugins:/{{ plugin_branch }}/xUbuntu_20.04/"
  vars_prompt:
    - name: plugin_branch
      prompt: Specify the cpanel-plugins branch name
      private: no

  tasks:
    - name: Prepare Ubuntu repository
      when: ansible_os_family == "Debian"
      file:
        path: "/etc/apt/sources.list.d/{{ repository_name }}.list"
        state: absent

    - name: Set internal cpanel-plugins repository
      import_tasks: common/tasks/configure_repository.yaml

    - name: Retain custom repo
      import_tasks: common/cpanel/retain_custom_repo.yaml